# Generated by Django 4.2.3 on 2023-08-05 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_electricistas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='electricistas',
        ),
    ]
