# Generated by Django 4.2.3 on 2023-08-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_carpinteros_cursoemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpinteros',
            old_name='cursoemail',
            new_name='email',
        ),
    ]
