# Generated by Django 4.2.3 on 2023-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_gasistas_pintores_plomeros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpinteros',
            name='precio',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
