# Generated by Django 4.2.3 on 2023-08-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_carpinteros_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpinteros',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
