# Generated by Django 4.2.3 on 2023-08-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_alter_carpinteros_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricistas',
            name='categoria',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='electricistas',
            name='matricula',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='electricistas',
            name='precio',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
