# Generated by Django 4.2.3 on 2023-08-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_gasistas_categoria_gasistas_matricula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasistas',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasistas',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasistas',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pintores',
            name='precio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plomeros',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plomeros',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plomeros',
            name='precio',
            field=models.CharField(max_length=50),
        ),
    ]
